language: android

sudo: false

android:
  components:
    - build-tools-28.0.1
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script: ./gradlew clean build --info
